type EmojiMap = { [key: string]: string }; // Interface for emoji key-value pairs

const realEmojis: { [category: string]: EmojiMap } = {
  People: {
    "grinning face": "😀",
    "grinning face with big eyes": "😃",
    "grinning face with smiling eyes": "😄",
    "beaming face with smiling eyes": "😁",
    "grinning squinting face": "😆",
    "grinning face with sweat": "😅",
    "rolling on the floor laughing": "🤣",
    "face with tears of joy": "😂",
    "slightly smiling face": "🙂",
    "upside-down face": "🙃",
    "face melting": "🫠",
    "winking face": "😉",
    "smiling face with smiling eyes": "😊",
    "smiling face with halo": "😇",
    "smiling face with hearts": "🥰",
    "heart eyes": "😍",
    "star-struck": "🤩",
    "face blowing a kiss": "😘",
    "kissing face": "😗",
    "smiling face": "☺️",
    "kissing face with closed eyes": "😚",
    "kissing face with smiling eyes": "😙",
    "smiling face with tear": "🥲",
    "yum face": "😋",
    "stuck-out tongue": "😛",
    "winking face with tongue": "😜",
    "zany face": "🤪",
    "squinting face with tongue": "😝",
    "money-mouth face": "🤑",
    "hugging face": "🤗",
    "face with hand over mouth": "🤭",
    "face with hidden eyes": "🫢",
    "face with peeking eye": "🫣",
    "shushing face": "🤫",
    "thinking face": "🤔",
    "saluting face": "🫡",
    "zipper-mouth face": "🤐",
    "raised eyebrow": "🤨",
    "neutral face": "😐",
    "expressionless face": "😑",
    "face without mouth": "😶",
    "face with diagonal mouth": "🫥",
    "cloudy face": "😶‍🌫️",
    "smirking face": "😏",
    "unamused face": "😒",
    "face with rolling eyes": "🙄",
    "grimacing face": "😬",
    "face exhaling": "😮‍💨",
    "lying face": "🤥",
    "shaking face": "🫨",
    "relieved face": "😌",
    "pensive face": "😔",
    "sleepy face": "😪",
    "drooling face": "🤤",
    "sleeping face": "😴",
    "face with medical mask": "😷",
    "face with thermometer": "🤒",
    "face with head-bandage": "🤕",
    "nauseated face": "🤢",
    "face vomiting": "🤮",
    "sneezing face": "🤧",
    "hot face": "🥵",
    "cold face": "🥶",
    "woozy face": "🥴",
    "dizzy face": "😵",
    "face with spiral eyes": "😵‍💫",
    "exploding head": "🤯",
    "cowboy hat face": "🤠",
    "partying face": "🥳",
    "disguised face": "🥸",
    "smiling face with sunglasses": "😎",
    "nerd face": "🤓",
    "face with monocle": "🧐",
    "confused face": "😕",
    "face with raised eyebrow": "🫤",
    "worried face": "😟",
    "slightly frowning face": "🙁",
    "frowning face": "☹️",
    "face with open mouth": "😮",
    "hushed face": "😯",
    "astonished face": "😲",
    "flushed face": "😳",
    "pleading face": "🥺",
    "face holding back tears": "🥹",
    "frowning face with open mouth": "😦",
    "anguished face": "😧",
    "fearful face": "😨",
    "anxious face with sweat": "😰",
    "sad but relieved face": "😥",
    "crying face": "😢",
    "loudly crying face": "😭",
    "face screaming in fear": "😱",
    "confounded face": "😖",
    "persevering face": "😣",
    "disappointed face": "😞",
    "downcast face with sweat": "😓",
    "weary face": "😩",
    "tired face": "😫",
    "yawning face": "🥱",
    "face with steam from nose": "😤",
    "angry face": "😡",
    "pouting face": "😠",
    "face with symbols on mouth": "🤬",
    "smiling face with horns": "😈",
    "angry face with horns": "👿",
    "skull": "💀",
    "skull and crossbones": "☠️",
    "pile of poo": "💩",
    "clown face": "🤡",
    "ogre": "👹",
    "goblin": "👺",
    "ghost": "👻",
    "alien": "👽",
    "alien monster": "👾",
    "waving hand": "👋",
    "raised back of hand": "🤚",
    "hand with fingers splayed": "🖐️",
    "raised hand": "✋",
    "vulcan salute": "🖖",
    "right-facing hand": "🫱",
    "left-facing hand": "🫲",
    "hand with palm up": "🫳",
    "hand with palm down": "🫴",
    "palm facing in": "🫷",
    "palm facing out": "🫸",
    "OK hand": "👌",
    "pinched fingers": "🤌",
    "pinching hand": "🤏",
    "victory hand": "✌️",
    "crossed fingers": "🤞",
    "hand with index Finger and thumb crossed": "🫰",
    "love-you gesture": "🤟",
    "rock on": "🤘",
    "call me hand": "🤙",
    "index pointing left": "👈",
    "index pointing right": "👉",
    "backhand index pointing up": "👆",
    "middle finger": "🖕",
    "index pointing down": "👇",
    "index pointing up": "☝️",
    "index pointing at you": "🫵",
    "thumbs up": "👍",
    "thumbs down": "👎",
    "raised fist": "✊",
    "fist": "👊",
    "left-facing fist": "🤛",
    "right-facing fist": "🤜",
    "clapping hands": "👏",
    "raising hands": "🙌",
    "heart hands": "🫶",
    "open hands": "👐",
    "palms up together": "🤲",
    "handshake": "🤝",
    "folded hands": "🙏",
    "writing hand": "✍️",
    "nail polish": "💅",
    "selfie": "🤳",
    "flexed bicep": "💪",
    "mechanical arm": "🦾",
    "mechanical leg": "🦿",
    "leg": "🦵",
    "foot": "🦶",
    "ear": "👂",
    "ear with hearing aid": "🦻",
    "nose": "👃",
    "brain": "🧠",
    "anatomical heart": "🫀",
    "lungs": "🫁",
    "tooth": "🦷",
    "bone": "🦴",
    "eyes": "👀",
    "eye": "👁️",
    "tongue": "👅",
    "lips": "👄",
    "biting lip": "🫦",
    "baby": "👶",
    "child": "🧒",
    "boy": "👦",
    "girl": "👧",
    "person": "🧑",
    "person with blond hair": "👱",
    "man": "👨",
    "man beard": "🧔",
    "man beard with medium skin tone": "🧔‍♂️",
    "woman beard": "🧔‍♀️",
    "man with red hair": "👨‍🦰",
    "man with curly hair": "👨‍🦱",
    "man with white hair": "👨‍🦳",
    "man with bald head": "👨‍🦲",
    "woman": "👩",
    "woman with red hair": "👩‍🦰",
    "person with red hair": "🧑‍🦰",
    "woman with curly hair": "👩‍🦱",
    "person with curly hair": "🧑‍🦱",
    "woman with white hair": "👩‍🦳",
    "person with white hair": "🧑‍🦳",
    "woman with bald head": "👩‍🦲",
    "person with bald head": "🧑‍🦲",
    "woman with blond hair": "👱‍♀️",
    "man with blond hair": "👱‍♂️",
    "older person": "🧓",
    "old man": "👴",
    "old woman": "👵",
    "person frowning": "🙍",
    "man frowning": "🙍‍♂️",
    "woman frowning": "🙍‍♀️",
    "person pouting": "🙎",
    "man pouting": "🙎‍♂️",
    "woman pouting": "🙎‍♀️",
    "person gesturing NO": "🙅",
    "man gesturing NO": "🙅‍♂️",
    "woman gesturing NO": "🙅‍♀️",
    "person gesturing OK": "🙆",
    "man gesturing OK": "🙆‍♂️",
    "woman gesturing OK": "🙆‍♀️",
    "person tipping hand": "💁",
    "man tipping hand": "💁‍♂️",
    "woman tipping hand": "💁‍♀️",
    "person raising hand": "🙋",
    "man raising hand": "🙋‍♂️",
    "woman raising hand": "🙋‍♀️",
    "person deaf": "🧏",
    "man deaf": "🧏‍♂️",
    "woman deaf": "🧏‍♀️",
    "person bowing": "🙇",
    "man bowing": "🙇‍♂️",
    "woman bowing": "🙇‍♀️",
    "person facepalming": "🤦",
    "man facepalming": "🤦‍♂️",
    "woman facepalming": "🤦‍♀️",
    "person shrugging": "🤷",
    "man shrugging": "🤷‍♂️",
    "woman shrugging": "🤷‍♀️",
    "health worker": "🧑‍⚕️",
    "man health worker": "👨‍⚕️",
    "woman health worker": "👩‍⚕️",
    "student": "🧑‍🎓",
    "man student": "👨‍🎓",
    "woman student": "👩‍🎓",
    "teacher": "🧑‍🏫",
    "man teacher": "👨‍🏫",
    "woman teacher": "👩‍🏫",
    "judge": "🧑‍⚖️",
    "man judge": "👨‍⚖️",
    "woman judge": "👩‍⚖️",
    "farmer": "🧑‍🌾",
    "man farmer": "👨‍🌾",
    "woman farmer": "👩‍🌾",
    "cook": "🧑‍🍳",
    "man cook": "👨‍🍳",
    "woman cook": "👩‍🍳",
    "mechanic": "🧑‍🔧",
    "man mechanic": "👨‍🔧",
    "woman mechanic": "👩‍🔧",
    "factory worker": "🧑‍🏭",
    "man factory worker": "👨‍🏭",
    "woman factory worker": "👩‍🏭",
    "office worker": "🧑‍💼",
    "man office worker": "👨‍💼",
    "woman office worker": "👩‍💼",
    "scientist": "🧑‍🔬",
    "man scientist": "👨‍🔬",
    "woman scientist": "👩‍🔬",
    "technologist": "🧑‍💻",
    "man technologist": "👨‍💻",
    "woman technologist": "👩‍💻",
    "singer": "🧑‍🎤",
    "man singer": "👨‍🎤",
    "woman singer": "👩‍🎤",
    "artist": "🧑‍🎨",
    "man artist": "👨‍🎨",
    "woman artist": "👩‍🎨",
    "pilot": "🧑‍✈️",
    "man pilot": "👨‍✈️",
    "woman pilot": "👩‍✈️",
    "astronaut": "🧑‍🚀",
    "man astronaut": "👨‍🚀",
    "woman astronaut": "👩‍🚀",
    "firefighter": "🧑‍🚒",
    "man firefighter": "👨‍🚒",
    "woman firefighter": "👩‍🚒",
    "police officer": "👮",
    "man police officer": "👮‍♂️",
    "woman police officer": "👮‍♀️",
    "detective": "🕵️",
    "man detective": "🕵️‍♂️",
    "woman detective": "🕵️‍♀️",
    "guard": "💂",
    "man guard": "💂‍♂️",
    "woman guard": "💂‍♀️",
    "ninja": "🥷",
    "construction worker": "👷",
    "man construction worker": "👷‍♂️",
    "woman construction worker": "👷‍♀️",
    "person with crown": "🫅",
    "prince": "🤴",
    "princess": "👸",
    "man with turban": "👳",
    "man with turban and medium skin tone": "👳‍♂️",
    "woman with turban": "👳‍♀️",
    "man with Chinese hat": "👲",
    "woman with headscarf": "🧕",
    "man in tuxedo": "🤵",
    "man in tuxedo with medium skin tone": "🤵‍♂️",
    "woman in tuxedo": "🤵‍♀️",
    "bride with veil": "👰",
    "man bride": "👰‍♂️",
    "woman bride": "👰‍♀️",
    "pregnant woman": "🤰",
    "person gestating": "🫃",
    "person gestating with medium skin tone": "🫄",
    "breastfeeding": "🤱",
    "woman feeding baby": "👩‍🍼",
    "man feeding baby": "👨‍🍼",
    "person feeding baby": "🧑‍🍼",
    "angel": "👼",
    "Santa Claus": "🎅",
    "Mrs. Claus": "🤶",
    "person in Santa costume": "🧑‍🎄",
    "superhero": "🦸",
    "man superhero": "🦸‍♂️",
    "woman superhero": "🦸‍♀️",
    "supervillain": "🦹",
    "man supervillain": "🦹‍♂️",
    "woman supervillain": "🦹‍♀️",
    "mage": "🧙",
    "man mage": "🧙‍♂️",
    "woman mage": "🧙‍♀️",
    "fairy": "🧚",
    "man fairy": "🧚‍♂️",
    "woman fairy": "🧚‍♀️",
    "vampire": "🧛",
    "man vampire": "🧛‍♂️",
    "woman vampire": "🧛‍♀️",
    "merperson": "🧜",
    "man merperson": "🧜‍♂️",
    "woman merperson": "🧜‍♀️",
    "elf": "🧝",
    "man elf": "🧝‍♂️",
    "woman elf": "🧝‍♀️",
    "genie": "🧞",
    "man genie": "🧞‍♂️",
    "woman genie": "🧞‍♀️",
    "zombie": "🧟",
    "man zombie": "🧟‍♂️",
    "woman zombie": "🧟‍♀️",
    "troll": "🧌",
    "person getting massage": "💆",
    "man getting massage": "💆‍♂️",
    "woman getting massage": "💆‍♀️",
    "person getting haircut": "💇",
    "man getting haircut": "💇‍♂️",
    "woman getting haircut": "💇‍♀️",
    "person walking": "🚶",
    "man walking": "🚶‍♂️",
    "woman walking": "🚶‍♀️",
    "person standing": "🧍",
    "man standing": "🧍‍♂️",
    "woman standing": "🧍‍♀️",
    "person kneeling": "🧎",
    "man kneeling": "🧎‍♂️",
    "woman kneeling": "🧎‍♀️",
    "person with cane": "🧑‍🦯",
    "man with cane": "👨‍🦯",
    "woman with cane": "👩‍🦯",
    "person in motorized wheelchair": "🧑‍🦼",
    "man in motorized wheelchair": "👨‍🦼",
    "woman in motorized wheelchair": "👩‍🦼",
    "person in manual wheelchair": "🧑‍🦽",
    "man in manual wheelchair": "👨‍🦽",
    "woman in manual wheelchair": "👩‍🦽",
    "person running": "🏃",
    "man running": "🏃‍♂️",
    "woman running": "🏃‍♀️",
    "dancer": "💃",
    "man dancing": "🕺",
    "businessman in tuxedo": "🕴️",
    "person with bunny ears": "👯",
    "man with bunny ears": "👯‍♂️",
    "woman with bunny ears": "👯‍♀️",
    "person in sauna": "🧖",
    "man in sauna": "🧖‍♂️",
    "woman in sauna": "🧖‍♀️",
    "person climbing": "🧗",
    "man climbing": "🧗‍♂️",
    "woman climbing": "🧗‍♀️",
    "person fencing": "🤺",
    "horse racing": "🏇",
    "skier": "⛷️",
    "snowboarder": "🏂",
    "golfer": "🏌️",
    "man golfing": "🏌️‍♂️",
    "woman golfing": "🏌️‍♀️",
    "surfer": "🏄",
    "man surfing": "🏄‍♂️",
    "woman surfing": "🏄‍♀️",
    "person rowing boat": "🚣",
    "man rowing boat": "🚣‍♂️",
    "woman rowing boat": "🚣‍♀️",
    "person swimming": "🏊",
    "man swimming": "🏊‍♂️",
    "woman swimming": "🏊‍♀️",
    "person bouncing ball": "⛹️",
    "man bouncing ball": "⛹️‍♂️",
    "woman bouncing ball": "⛹️‍♀️",
    "person weightlifting": "🏋️",
    "man weightlifting": "🏋️‍♂️",
    "woman weightlifting": "🏋️‍♀️",
    "person biking": "🚴",
    "man biking": "🚴‍♂️",
    "woman biking": "🚴‍♀️",
    "person mountain biking": "🚵",
    "man mountain biking": "🚵‍♂️",
    "woman mountain biking": "🚵‍♀️",
    "person cartwheeling": "🤸",
    "man cartwheeling": "🤸‍♂️",
    "woman cartwheeling": "🤸‍♀️",
    "person wrestling": "🤼",
    "man wrestling": "🤼‍♂️",
    "woman wrestling": "🤼‍♀️",
    "person water polo": "🤽",
    "man water polo": "🤽‍♂️",
    "woman water polo": "🤽‍♀️",
    "person playing handball": "🤾",
    "man playing handball": "🤾‍♂️",
    "woman playing handball": "🤾‍♀️",
    "person juggling": "🤹",
    "man juggling": "🤹‍♂️",
    "woman juggling": "🤹‍♀️",
    "person meditating": "🧘",
    "man meditating": "🧘‍♂️",
    "woman meditating": "🧘‍♀️",
    "person taking a bath": "🛀",
    "person sleeping in bed": "🛌",
    "people holding hands": "🧑‍🤝‍🧑",
    "two women holding hands": "👭",
    "man and woman holding hands": "👫",
    "two men holding hands": "👬",
    "kiss": "💏",
    "woman kissing man": "👩‍❤️‍💋‍👨",
    "man kissing man": "👨‍❤️‍💋‍👨",
    "woman kissing woman": "👩‍❤️‍💋‍👩",
    "couple with heart": "💑",
    "woman with heart and man": "👩‍❤️‍👨",
    "man with heart and man": "👨‍❤️‍👨",
    "woman with heart and woman": "👩‍❤️‍👩",
    "family": "👪",
    "man, woman, and boy": "👨‍👩‍👦",
    "man, woman, and girl": "👨‍👩‍👧",
    "man, woman, and children": "👨‍👩‍👧‍👦",
    "man, woman, and multiple boys": "👨‍👩‍👦‍👦",
    "man, woman, and multiple girls": "👨‍👩‍👧‍👧",
    "two men and a boy": "👨‍👨‍👦",
    "two men and a girl": "👨‍👨‍👧",
    "two men and children": "👨‍👨‍👧‍👦",
    "two men and multiple boys": "👨‍👨‍👦‍👦",
    "two men and multiple girls": "👨‍👨‍👧‍👧",
    "two women and a boy": "👩‍👩‍👦",
    "two women and a girl": "👩‍👩‍👧",
    "two women and children": "👩‍👩‍👧‍👦",
    "two women and multiple boys": "👩‍👩‍👦‍👦",
    "two women and multiple girls": "👩‍👩‍👧‍👧",
    "man and boy": "👨‍👦",
    "man and multiple boys": "👨‍👦‍👦",
    "man and girl": "👨‍👧",
    "man and girl with boy": "👨‍👧‍👦",
    "man and girl with girl": "👨‍👧‍👧",
    "woman and boy": "👩‍👦",
    "woman and multiple boys": "👩‍👦‍👦",
    "woman and girl": "👩‍👧",
    "woman and girl with boy": "👩‍👧‍👦",
    "woman and girl with girl": "👩‍👧‍👧",
    "speaking head": "🗣️",
    "bust in silhouette": "👤",
    "busts in silhouette": "👥",
    "people hugging": "🫂",
    "footprints": "👣",
    "robot": "🤖",
    "smiling cat": "😺",
    "grinning cat": "😸",
    "cat with tears of joy": "😹",
    "heart eyes cat": "😻",
    "cat with wry smile": "😼",
    "kissing cat": "😽",
    "weary cat": "🙀",
    "crying cat": "😿",
    "pouting cat": "😾",
    "see-no-evil monkey": "🙈",
    "hear-no-evil monkey": "🙉",
    "speak-no-evil monkey": "🙊",
    "love letter": "💌",
    "heart with arrow": "💘",
    "heart with ribbon": "💝",
    "sparkling heart": "💖",
    "growing heart": "💗",
    "beating heart": "💓",
    "revolving hearts": "💞",
    "two hearts": "💕",
    "heart with exclamation": "💟",
    "heart exclamation": "❣️",
    "broken heart": "💔",
    "heart on fire": "❤️‍🔥",
    "mending heart": "❤️‍🩹",
    "red heart": "❤️",
    "pink heart": "🩷",
    "orange heart": "🧡",
    "yellow heart": "💛",
    "green heart": "💚",
    "blue heart": "💙",
    "blue heart with ribbon": "🩵",
    "purple heart": "💜",
    "brown heart": "🤎",
    "black heart": "🖤",
    "white heart": "🩶",
    "white heart with ribbon": "🤍",
    "kiss mark": "💋",
    "hundred points": "💯",
    "anger symbol": "💢",
    "collision": "💥",
    "dizzy": "💫",
    "sweat droplets": "💦",
    "dashing away": "💨",
    "hole": "🕳️",
    "speech balloon": "💬",
    "eye in speech bubble": "👁️‍🗨️",
    "left speech balloon": "🗨️",
    "thought balloon": "🗯️",
    "thought bubble": "💭",
    "zzz": "💤"
  },
  Food: {
    "grapes": "🍇",
    "melon": "🍈",
    "watermelon": "🍉",
    "tangerine": "🍊",
    "lemon": "🍋",
    "lime": "🍋‍🟩",
    "banana": "🍌",
    "pineapple": "🍍",
    "mango": "🥭",
    "apple": "🍎",
    "green apple": "🍏",
    "pear": "🍐",
    "peach": "🍑",
    "cherries": "🍒",
    "strawberry": "🍓",
    "blueberry": "🫐",
    "kiwi": "🥝",
    "tomato": "🍅",
    "olive": "🫒",
    "coconut": "🥥",
    "avocado": "🥑",
    "eggplant": "🍆",
    "potato": "🥔",
    "carrot": "🥕",
    "ear of corn": "🌽",
    "hot pepper": "🌶️",
    "bell pepper": "🫑",
    "cucumber": "🥒",
    "leafy green": "🥬",
    "broccoli": "🥦",
    "garlic": "🧄",
    "onion": "🧅",
    "peanuts": "🥜",
    "beans": "🫘",
    "chestnut": "🌰",
    "pea pod": "🫚",
    "sugar snap pea": "🫛",
    "mushroom": "🍄‍🟫",
    "bread": "🍞",
    "croissant": "🥐",
    "baguette": "🥖",
    "rock": "🫓",
    "pretzel": "🥨",
    "bagel": "🥯",
    "pancakes": "🥞",
    "waffle": "🧇",
    "cheese wedge": "🧀",
    "meat on bone": "🍖",
    "poultry leg": "🍗",
    "steak": "🥩",
    "bacon": "🥓",
    "hamburger": "🍔",
    "fries": "🍟",
    "pizza": "🍕",
    "hot dog": "🌭",
    "sandwich": "🥪",
    "taco": "🌮",
    "burrito": "🌯",
    "tamale": "🫔",
    "stuffed flatbread": "🥙",
    "falafel": "🧆",
    "egg": "🥚",
    "cooking": "🍳",
    "shallow pan of food": "🥘",
    "pot of food": "🍲",
    "fondue": "🫕",
    "bowl with spoon": "🥣",
    "green salad": "🥗",
    "popcorn": "🍿",
    "butter": "🧈",
    "salt": "🧂",
    "canned food": "🥫",
    "spaghetti": "🍝",
    "bento box": "🍱",
    "rice cracker": "🍘",
    "rice ball": "🍙",
    "cooked rice": "🍚",
    "curry rice": "🍛",
    "steaming bowl": "🍜",
    "sweet potato": "🍠",
    "skewer": "🍢",
    "sushi": "🍣",
    "fried shrimp": "🍤",
    "fish cake": "🍥",
    "moon cake": "🥮",
    "dango": "🍡",
    "dumpling": "🥟",
    "fortune cookie": "🥠",
    "takeout box": "🥡",
    "ice cream": "🍦",
    "shaved ice": "🍧",
    "ice cream sundae": "🍨",
    "doughnut": "🍩",
    "cookie": "🍪",
    "birthday cake": "🎂",
    "shortcake": "🍰",
    "cupcake": "🧁",
    "pie": "🥧",
    "chocolate bar": "🍫",
    "candy": "🍬",
    "lollipop": "🍭",
    "custard": "🍮",
    "honey": "🍯",
    "baby bottle": "🍼",
    "milk glass": "🥛",
    "hot beverage": "☕",
    "teapot": "🫖",
    "tea": "🍵",
    "sake": "🍶",
    "bottle with popping cork": "🍾",
    "wine glass": "🍷",
    "cocktail glass": "🍸",
    "tropical drink": "🍹",
    "beer mug": "🍺",
    "beer": "🍻",
    "clinking glasses": "🥂",
    "tumbler glass": "🥃",
    "pouring liquid": "🫗",
    "cup with straw": "🥤",
    "bubble tea": "🧋",
    "juice box": "🧃",
    "smoothie": "🧉",
    "chopsticks": "🥢",
    "plate": "🍽️",
    "fork and knife": "🍴",
    "spoon": "🥄",
    "kitchen knife": "🔪",
    "jar": "🫙",
    "amphora": "🏺"
  },
  Nature: {
    "monkey": "🐵",
    "monkey face": "🐒",
    "gorilla": "🦍",
    "orangutan": "🦧",
    "dog": "🐶",
    "dog with tail": "🐕",
    "guide dog": "🦮",
    "service dog": "🐕‍🦺",
    "poodle": "🐩",
    "wolf": "🐺",
    "fox": "🦊",
    "raccoon": "🦝",
    "cat face": "🐱",
    "cat": "🐈",
    "black cat": "🐈‍⬛",
    "lion": "🦁",
    "tiger": "🐯",
    "tiger face": "🐅",
    "leopard": "🐆",
    "horse": "🐴",
    "moose": "🫎",
    "donkey": "🫏",
    "racing horse": "🐎",
    "unicorn": "🦄",
    "zebra": "🦓",
    "deer": "🦌",
    "bison": "🦬",
    "cow face": "🐮",
    "ox": "🐂",
    "water buffalo": "🐃",
    "cow": "🐄",
    "pig": "🐷",
    "pig face": "🐖",
    "boar": "🐗",
    "pig nose": "🐽",
    "ram": "🐏",
    "sheep": "🐑",
    "goat": "🐐",
    "camel": "🐪",
    "two-humped camel": "🐫",
    "lama": "🦙",
    "giraffe": "🦒",
    "elephant": "🐘",
    "mammoth": "🦣",
    "rhinoceros": "🦏",
    "hippopotamus": "🦛",
    "mouse face": "🐭",
    "mouse": "🐁",
    "rat": "🐀",
    "hamster": "🐹",
    "rabbit face": "🐰",
    "rabbit": "🐇",
    "chipmunk": "🐿️",
    "beaver": "🦫",
    "hedgehog": "🦔",
    "bat": "🦇",
    "bear": "🐻",
    "polar bear": "🐻‍❄️",
    "koala": "🐨",
    "panda": "🐼",
    "sloth": "🦥",
    "otter": "🦦",
    "skunk": "🦨",
    "kangaroo": "🦘",
    "badger": "🦡",
    "paw prints": "🐾",
    "turkey": "🦃",
    "chicken": "🐔",
    "rooster": "🐓",
    "hatching chick": "🐣",
    "baby chick": "🐤",
    "front-facing baby chick": "🐥",
    "bird": "🐦",
    "penguin": "🐧",
    "dove": "🕊️",
    "eagle": "🦅",
    "duck": "🦆",
    "swan": "🦢",
    "owl": "🦉",
    "dodo": "🦤",
    "peacock": "🦩",
    "peacock feather": "🦚",
    "parrot": "🦜",
    "wings": "🪽",
    "black bird": "🐦‍⬛",
    "goose": "🪿",
    "firebird": "🐦‍🔥",
    "nesting": "🪹",
    "bird's nest": "🪺",
    "frog": "🐸",
    "crocodile": "🐊",
    "turtle": "🐢",
    "lizard": "🦎",
    "snake": "🐍",
    "dragon face": "🐲",
    "dragon": "🐉",
    "sauropod": "🦕",
    "tyrannosaurus rex": "🦖",
    "spouting whale": "🐳",
    "whale": "🐋",
    "dolphin": "🐬",
    "seal": "🦭",
    "fish": "🐟",
    "tropical fish": "🐠",
    "blowfish": "🐡",
    "shark": "🦈",
    "octopus": "🐙",
    "shell": "🐚",
    "coral": "🪸",
    "sea urchin": "🪼",
    "crab": "🦀",
    "lobster": "🦞",
    "shrimp": "🦐",
    "squid": "🦑",
    "oyster": "🦪",
    "snail": "🐌",
    "butterfly": "🦋",
    "bug": "🐛",
    "ant": "🐜",
    "bee": "🐝",
    "beetle": "🪲",
    "ladybug": "🐞",
    "grasshopper": "🦗",
    "cockroach": "🪳",
    "spider": "🕷️",
    "spider web": "🕸️",
    "scorpion": "🦂",
    "mosquito": "🦟",
    "fly": "🪰",
    "worm": "🪱",
    "microbe": "🦠",
    "bouquet": "💐",
    "cherry blossom": "🌸",
    "white flower": "💮",
    "lotus": "🪷",
    "rosette": "🏵️",
    "rose": "🌹",
    "wilted flower": "🥀",
    "hibiscus": "🌺",
    "sunflower": "🌻",
    "blossom": "🌼",
    "tulip": "🌷",
    "flower": "🪻",
    "seedling": "🌱",
    "potted plant": "🪴",
    "evergreen tree": "🌲",
    "deciduous tree": "🌳",
    "palm tree": "🌴",
    "cactus": "🌵",
    "sheaf of rice": "🌾",
    "herb": "🌿",
    "shamrock": "☘️",
    "four leaf clover": "🍀",
    "maple leaf": "🍁",
    "fallen leaf": "🍂",
    "leaf fluttering in wind": "🍃",
    "mushroom": "🍄",
    "rock": "🪨",
    "wood": "🪵",
    "new moon": "🌑",
    "waxing crescent moon": "🌒",
    "first quarter moon": "🌓",
    "waxing gibbous moon": "🌔",
    "full moon": "🌕",
    "waning gibbous moon": "🌖",
    "last quarter moon": "🌗",
    "waning crescent moon": "🌘",
    "crescent moon": "🌙",
    "moon face": "🌚",
    "first quarter moon face": "🌛",
    "last quarter moon face": "🌜",
    "sun": "☀️",
    "full moon with face": "🌝",
    "sun with face": "🌞",
    "ringed planet": "🪐",
    "star": "⭐",
    "glowing star": "🌟",
    "shooting star": "🌠",
    "milky way": "🌌",
    "cloud": "☁️",
    "sun behind cloud": "⛅",
    "cloud with rain": "⛈️",
    "sun behind small cloud": "🌤️",
    "sun behind large cloud": "🌥️",
    "sun behind rain cloud": "🌦️",
    "cloud with lightning and rain": "🌧️",
    "cloud with snow": "🌨️",
    "cloud with lightning": "🌩️",
    "tornado": "🌪️",
    "fog": "🌫️",
    "wind face": "🌬️",
    "cyclone": "🌀",
    "rainbow": "🌈",
    "closed umbrella": "🌂",
    "umbrella with rain drops": "☂️",
    "umbrella": "☔",
    "beach umbrella": "⛱️",
    "high voltage": "⚡",
    "snowflake": "❄️",
    "snowman": "☃️",
    "snowman without snow": "⛄",
    "comet": "☄️",
    "fire": "🔥",
    "droplet": "💧",
    "water wave": "🌊"
  },
  Activities: {
    "soccer": "⚽️",
    "basketball": "🏀",
    "football": "🏈",
    "baseball": "⚾️",
    "softball": "🥎",
    "tennis": "🎾",
    "volleyball": "🏐",
    "rugby": "🏉",
    "frisbee": "🥏",
    "pool": "🎱",
    "top": "🪀",
    "table tennis": "🏓",
    "badminton": "🏸",
    "ice hockey": "🏒",
    "field hockey": "🏑",
    "lacrosse": "🥍",
    "cricket": "🏏",
    "archery": "🪃",
    "goal": "🥅",
    "golf": "⛳️",
    "kite": "🪁",
    "archery target": "🏹",
    "fishing": "🎣",
    "diving": "🤿",
    "boxing": "🥊",
    "karate": "🥋",
    "running shirt": "🎽",
    "skateboarding": "🛹",
    "roller skating": "🛼",
    "sledding": "🛷",
    "ice skating": "⛸",
    "curling": "🥌",
    "skiing": "🎿",
    "skier": "⛷",
    "snowboarding": "🏂",
    "paragliding": "🪂",
    "weightlifting female": "🏋️‍♀️",
    "weightlifting": "🏋️",
    "weightlifting male": "🏋️‍♂️",
    "wrestling female": "🤼‍♀️",
    "wrestling": "🤼",
    "wrestling male": "🤼‍♂️",
    "gymnastics female": "🤸‍♀️",
    "gymnastics": "🤸",
    "gymnastics male": "🤸‍♂️",
    "basketball female": "⛹️‍♀️",
    "basketball male": "⛹️‍♂️",
    "fencing": "🤺",
    "handball female": "🤾‍♀️",
    "handball": "🤾",
    "handball male": "🤾‍♂️",
    "golf female": "🏌️‍♀️",
    "man golfing": "🏌️",
    "golf male": "🏌️‍♂️",
    "horse riding": "🏇",
    "yoga female": "🧘‍♀️",
    "yoga": "🧘",
    "yoga male": "🧘‍♂️",
    "surfing female": "🏄‍♀️",
    "surfing": "🏄",
    "surfing male": "🏄‍♂️",
    "swimming female": "🏊‍♀️",
    "swimming": "🏊",
    "swimming male": "🏊‍♂️",
    "water polo female": "🤽‍♀️",
    "water polo": "🤽",
    "water polo male": "🤽‍♂️",
    "rowing female": "🚣‍♀️",
    "rowing": "🚣",
    "rowing male": "🚣‍♂️",
    "rock climbing female": "🧗‍♀️",
    "rock climbing": "🧗",
    "rock climbing male": "🧗‍♂️",
    "mountain biking female": "🚵‍♀️",
    "mountain biking": "🚵",
    "mountain biking male": "🚵‍♂️",
    "cycling female": "🚴‍♀️",
    "cycling": "🚴",
    "cycling male": "🚴‍♂️",
    "trophy": "🏆",
    "medal 1st": "🥇",
    "medal 2nd": "🥈",
    "medal 3rd": "🥉",
    "medal": "🏅",
    "military medal": "🎖",
    "rosette": "🏵",
    "reminder ribbon": "🎗",
    "ticket": "🎫",
    "admission ticket": "🎟",
    "circus tent": "🎪",
    "juggling": "🤹",
    "juggling male": "🤹‍♂️",
    "juggling female": "🤹‍♀️",
    "performing arts": "🎭",
    "ballet": "🩰",
    "art": "🎨",
    "film projector": "🎬",
    "microphone": "🎤",
    "headphones": "🎧",
    "musical score": "🎼",
    "piano": "🎹",
    "drum": "🥁",
    "musical instrument": "🪘",
    "maraca": "🪇",
    "saxophone": "🎷",
    "trumpet": "🎺",
    "accordion": "🪗",
    "guitar": "🎸",
    "banjo": "🪕",
    "violin": "🎻",
    "flute": "🪈",
    "dice": "🎲",
    "chess": "♟",
    "dart": "🎯",
    "bowling": "🎳",
    "video game": "🎮",
    "slot machine": "🎰",
    "puzzle piece": "🧩"
  },
  Travel: {
    "car": "🚗",
    "taxi": "🚕",
    "minivan": "🚙",
    "bus": "🚌",
    "trolley bus": "🚎",
    "racing car": "🏎",
    "police car": "🚓",
    "ambulance": "🚑",
    "fire truck": "🚒",
    "van": "🚐",
    "pickup truck": "🛻",
    "delivery truck": "🚚",
    "articulated truck": "🚛",
    "tractor": "🚜",
    "white cane": "🦯",
    "manual wheelchair": "🦽",
    "motorized wheelchair": "🦼",
    "kick scooter": "🛴",
    "bicycle": "🚲",
    "motorbike": "🛵",
    "motorcycle": "🏍",
    "auto rickshaw": "🛺",
    "light bar": "🚨",
    "police car light": "🚔",
    "bus stop": "🚍",
    "oncoming car": "🚘",
    "oncoming taxi": "🚖",
    "wheel": "🛞",
    "cable car": "🚡",
    "mountain cableway": "🚠",
    "suspension railway": "🚟",
    "railway car": "🚃",
    "railway tram": "🚋",
    "mountain railway": "🚞",
    "high speed train": "🚝",
    "train": "🚄",
    "bullet train": "🚅",
    "light rail": "🚈",
    "steam locomotive": "🚂",
    "train car": "🚆",
    "metro": "🚇",
    "tram": "🚊",
    "station": "🚉",
    "airplane": "✈️",
    "airplane departure": "🛫",
    "airplane arrival": "🛬",
    "small airplane": "🛩",
    "seat": "💺",
    "satellite": "🛰",
    "rocket": "🚀",
    "flying saucer": "🛸",
    "helicopter": "🚁",
    "canoe": "🛶",
    "sailboat": "⛵️",
    "motorboat": "🚤",
    "yacht": "🛥",
    "cruise ship": "🛳",
    "ferry": "⛴",
    "ship": "🚢",
    "anchor": "⚓️",
    "lifebuoy": "🛟",
    "hook": "🪝",
    "fuel pump": "⛽️",
    "construction": "🚧",
    "traffic light": "🚦",
    "vertical traffic light": "🚥",
    "bus stop sign": "🚏",
    "world map": "🗺",
    "moai": "🗿",
    "statue of liberty": "🗽",
    "eiffel tower": "🗼",
    "castle": "🏰",
    "japanese castle": "🏯",
    "stadium": "🏟",
    "ferris wheel": "🎡",
    "roller coaster": "🎢",
    "slide": "🛝",
    "carousel horse": "🎠",
    "fountain": "⛲️",
    "umbrella on ground": "⛱",
    "beach with umbrella": "🏖",
    "desert island": "🏝",
    "desert": "🏜",
    "volcano": "🌋",
    "mountain": "⛰",
    "snow capped mountain": "🏔",
    "mount fuji": "🗻",
    "camping": "🏕",
    "tent": "⛺️",
    "house": "🏠",
    "house with garden": "🏡",
    "houses": "🏘",
    "derelict house": "🏚",
    "construction site": "🏗",
    "factory": "🏭",
    "office building": "🏢",
    "department store": "🏬",
    "post office": "🏣",
    "hospital": "🏥",
    "bank": "🏦",
    "hotel": "🏨",
    "convenience store": "🏪",
    "school": "🏫",
    "love hotel": "🏩",
    "wedding": "💒",
    "classical building": "🏛",
    "church": "⛪️",
    "mosque": "🕌",
    "synagogue": "🕍",
    "hindu temple": "🛕",
    "kaaba": "🕋",
    "shrine": "⛩",
    "railway track": "🛤",
    "motorway": "🛣",
    "map": "🗾",
    "shinto shrine": "🎑",
    "national park": "🏞",
    "sunrise": "🌅",
    "sunrise over mountains": "🌄",
    "shooting star": "🌠",
    "fireworks": "🎇",
    "fireworks 2": "🎆",
    "city sunset": "🌇",
    "cityscape": "🌆",
    "city": "🏙",
    "night with stars": "🌃",
    "milky way": "🌌",
    "bridge at night": "🌉",
    "foggy": "🌁"
  },
  Objects: {
    "watch": "⌚️",
    "mobile phone": "📱",
    "mobile phone with arrow": "📲",
    "laptop": "💻",
    "keyboard": "⌨️",
    "desktop computer": "🖥",
    "printer": "🖨",
    "computer mouse": "🖱",
    "trackball": "🖲",
    "joystick": "🕹",
    "clamp": "🗜",
    "floppy disk": "💽",
    "hard disk": "💾",
    "optical disc": "💿",
    "dvd": "📀",
    "videotape": "📼",
    "camera": "📷",
    "camera with flash": "📸",
    "video camera": "📹",
    "movie camera": "🎥",
    "film projector": "📽",
    "film frames": "🎞",
    "telephone receiver": "📞",
    "telephone": "☎️",
    "pager": "📟",
    "fax machine": "📠",
    "television": "📺",
    "radio": "📻",
    "microphone": "🎙",
    "level slider": "🎚",
    "control knobs": "🎛",
    "compass": "🧭",
    "stopwatch": "⏱",
    "timer": "⏲",
    "alarm clock": "⏰",
    "mantelpiece clock": "🕰",
    "hourglass": "⌛️",
    "hourglass with flowing sand": "⏳",
    "satellite antenna": "📡",
    "battery": "🔋",
    "low battery": "🪫",
    "electric plug": "🔌",
    "light bulb": "💡",
    "flashlight": "🔦",
    "candle": "🕯",
    "lamp": "🪔",
    "fire extinguisher": "🧯",
    "oil drum": "🛢",
    "shopping bags": "🛍️",
    "money with wings": "💸",
    "dollar banknote": "💵",
    "yen banknote": "💴",
    "euro banknote": "💶",
    "pound banknote": "💷",
    "coin": "🪙",
    "money bag": "💰",
    "credit card": "💳",
    "gem stone": "💎",
    "balance scale": "⚖️",
    "comb": "🪮",
    "ladder": "🪜",
    "toolbox": "🧰",
    "screwdriver": "🪛",
    "wrench": "🔧",
    "hammer": "🔨",
    "pick": "⚒",
    "hammer and pick": "🛠",
    "shovel": "⛏",
    "saw": "🪚",
    "nut and bolt": "🔩",
    "gear": "⚙️",
    "mouse trap": "🪤",
    "brick": "🧱",
    "chains": "⛓",
    "chains with explosion": "⛓️‍💥",
    "magnet": "🧲",
    "gun": "🔫",
    "bomb": "💣",
    "firecracker": "🧨",
    "axe": "🪓",
    "knife": "🔪",
    "dagger": "🗡",
    "crossed swords": "⚔️",
    "shield": "🛡",
    "cigarette": "🚬",
    "coffin": "⚰️",
    "headstone": "🪦",
    "funeral urn": "⚱️",
    "amphora": "🏺",
    "crystal ball": "🔮",
    "prayer beads": "📿",
    "nazar amulet": "🧿",
    "hamsa": "🪬",
    "barber pole": "💈",
    "alembic": "⚗️",
    "telescope": "🔭",
    "microscope": "🔬",
    "hole": "🕳",
    "drop of blood": "🩹",
    "stethoscope": "🩺",
    "x-ray": "🩻",
    "blood bag": "🩼",
    "pill": "💊",
    "syringe": "💉",
    "blood": "🩸",
    "dna": "🧬",
    "microbe": "🦠",
    "petri dish": "🧫",
    "test tube": "🧪",
    "thermometer": "🌡",
    "broom": "🧹",
    "plunger": "🪠",
    "basket": "🧺",
    "roll of toilet paper": "🧻",
    "toilet": "🚽",
    "potable water": "🚰",
    "shower": "🚿",
    "bathtub": "🛁",
    "person taking bath": "🛀",
    "soap": "🧼",
    "toothbrush": "🪥",
    "razor": "🪒",
    "sponge": "🧽",
    "bucket": "🪣",
    "lotion bottle": "🧴",
    "bellhop bell": "🛎",
    "key": "🔑",
    "old key": "🗝",
    "door": "🚪",
    "chair": "🪑",
    "couch and lamp": "🛋",
    "bed": "🛏",
    "person sleeping": "🛌",
    "teddy bear": "🧸",
    "nesting dolls": "🪆",
    "framed picture": "🖼",
    "mirror": "🪞",
    "window": "🪟",
    "shopping bags 2": "🛍",
    "shopping cart": "🛒",
    "gift": "🎁",
    "balloon": "🎈",
    "carp streamer": "🎏",
    "ribbon": "🎀",
    "magic wand": "🪄",
    "piñata": "🪅",
    "confetti ball": "🎊",
    "party popper": "🎉",
    "sparkler": "🪩",
    "Japanese dolls": "🎎",
    "lantern": "🏮",
    "wind chime": "🎐",
    "red envelope": "🧧",
    "envelope": "✉️",
    "envelope with arrow": "📩",
    "incoming envelope": "📨",
    "envelope with down arrow": "📧",
    "love letter": "💌",
    "incoming inbox tray": "📥",
    "outbox tray": "📤",
    "package": "📦",
    "label": "🏷",
    "bookmark": "🪧",
    "mailbox": "📪",
    "mailbox with raised flag": "📫",
    "open mailbox": "📬",
    "closed mailbox": "📭",
    "postbox": "📮",
    "postal horn": "📯",
    "scroll": "📜",
    "page with curl": "📃",
    "page facing up": "📄",
    "bookmark tabs": "📑",
    "receipt": "🧾",
    "bar chart": "📊",
    "chart increasing": "📈",
    "chart decreasing": "📉",
    "spiral notepad": "🗒",
    "calendar": "🗓",
    "tear-off calendar": "📆",
    "calendar page": "📅",
    "wastebasket": "🗑",
    "identification card": "🪪",
    "card index": "📇",
    "card file box": "🗃",
    "ballot box with ballot": "🗳",
    "file cabinet": "🗄",
    "clipboard": "📋",
    "file folder": "📁",
    "open file folder": "📂",
    "card index dividers": "🗂",
    "newspaper": "🗞",
    "rolled-up newspaper": "📰",
    "notebook": "📓",
    "bound notebook": "📔",
    "ledger": "📒",
    "open book": "📕",
    "green book": "📗",
    "blue book": "📘",
    "orange book": "📙",
    "books": "📚",
    "book": "📖",
    "bookmark 2": "🔖",
    "safety pin": "🧷",
    "link": "🔗",
    "paperclip": "📎",
    "paperclip 2": "🖇",
    "triangular ruler": "📐",
    "straight ruler": "📏",
    "abacus": "🧮",
    "pushpin": "📌",
    "round pushpin": "📍",
    "scissors": "✂️",
    "pen": "🖊",
    "fountain pen": "🖋",
    "black nib": "✒️",
    "paintbrush": "🖌",
    "crayon": "🖍",
    "memo": "📝",
    "pencil": "✏️",
    "magnifying glass tilted left": "🔍",
    "magnifying glass tilted right": "🔎",
    "lock with ink pen": "🔏",
    "closed lock with key": "🔐",
    "locked": "🔒",
    "open lock": "🔓"
  },
  Symbols: {
    "red heart": "❤️",
    "pink heart": "🩷",
    "orange heart": "🧡",
    "yellow heart": "💛",
    "green heart": "💚",
    "blue heart": "💙",
    "light blue heart": "🩵",
    "purple heart": "💜",
    "black heart": "🖤",
    "brown heart": "🩶",
    "white heart": "🤍",
    "dark brown heart": "🤎",
    "heart on fire": "❤️‍🔥",
    "mending heart": "❤️‍🩹",
    "broken heart": "💔",
    "heart exclamation": "❣️",
    "two hearts": "💕",
    "revolving hearts": "💞",
    "beating heart": "💓",
    "growing heart": "💗",
    "sparkling heart": "💖",
    "heart with arrow": "💘",
    "heart with ribbon": "💝",
    "heart decoration": "💟",
    "peace symbol": "☮️",
    "cross": "✝️",
    "star and crescent": "☪️",
    "hinduism": "🪯",
    "om": "🕉",
    "wheel of dharma": "☸️",
    "star of David": "✡️",
    "six-pointed star": "🔯",
    "menorah": "🕎",
    "yin yang": "☯️",
    "Orthodox cross": "☦️",
    "place of worship": "🛐",
    "Ophiuchus": "⛎",
    "Aries": "♈️",
    "Taurus": "♉️",
    "Gemini": "♊️",
    "Cancer": "♋️",
    "Leo": "♌️",
    "Virgo": "♍️",
    "Libra": "♎️",
    "Scorpio": "♏️",
    "Sagittarius": "♐️",
    "Capricorn": "♑️",
    "Aquarius": "♒️",
    "Pisces": "♓️",
    "ID": "🆔",
    "recycling symbol": "⚛️",
    "Japanese B button": "🉑",
    "radioactive": "☢️",
    "biohazard": "☣️",
    "mobile phone off": "📴",
    "vibration mode": "📳",
    "Japanese here button": "🈶",
    "Japanese not free button": "🈚️",
    "Japanese application button": "🈸",
    "Japanese open for business button": "🈺",
    "Japanese monthly amount button": "🈷️",
    "eight-pointed star": "✴️",
    "versus": "🆚",
    "white flower": "💮",
    "Japanese free of charge button": "🉐",
    "secret": "㊙️",
    "congratulations": "㊗️",
    "Japanese pass button": "🈴",
    "Japanese full button": "🈵",
    "Japanese discount button": "🈹",
    "Japanese prohibited button": "🈲",
    "blood type A": "🅰️",
    "blood type B": "🅱️",
    "blood type AB": "🆎",
    "blood type O": "🆑",
    "negative squared latin capital letter O": "🅾️",
    "sos": "🆘",
    "cross mark": "❌",
    "heavy large circle": "⭕️",
    "stop sign": "🛑",
    "prohibited": "⛔️",
    "name badge": "📛",
    "no entry": "🚫",
    "hundred points": "💯",
    "anger symbol": "💢",
    "hot springs": "♨️",
    "no pedestrians": "🚷",
    "no littering": "🚯",
    "no bicycles": "🚳",
    "no drinking": "🚱",
    "adult": "🔞",
    "no mobile phones": "📵",
    "no smoking": "🚭",
    "exclamation mark": "❗️",
    "white exclamation mark": "❕",
    "question mark": "❓",
    "white question mark": "❔",
    "double exclamation mark": "‼️",
    "exclamation question mark": "⁉️",
    "dim button": "🔅",
    "bright button": "🔆",
    "part alternation mark": "〽️",
    "warning": "⚠️",
    "children crossing": "🚸",
    "trident emblem": "🔱",
    "fleur-de-lis": "⚜️",
    "beginner": "🔰",
    "recycle": "♻️",
    "check mark": "✅",
    "Japanese reserved button": "🈯️",
    "chart with upward trend": "💹",
    "sparkles": "❇️",
    "eight-pointed star 2": "✳️",
    "cross mark button": "❎",
    "globe with meridians": "🌐",
    "diamond with a dot": "💠",
    "circled M": "Ⓜ️",
    "cyclone": "🌀",
    "zzz": "💤",
    "ATM": "🏧",
    "potable water": "🚾",
    "wheelchair symbol": "♿️",
    "parking": "🅿️",
    "elevator": "🛗",
    "Japanese reserved button 2": "🈳",
    "Japanese service charge button": "🈂️",
    "customs": "🛂",
    "passport control": "🛃",
    "baggage claim": "🛄",
    "left luggage": "🛅",
    "man symbol": "🚹",
    "woman symbol": "🚺",
    "baby symbol": "🚼",
    "transgender symbol": "⚧",
    "restroom": "🚻",
    "litter in bin sign": "🚮",
    "cinema": "🎦",
    "label": "🛜",
    "antenna with bars": "📶",
    "Japanese sos button": "🈁",
    "input symbols": "🔣",
    "information": "ℹ️",
    "input latin lowercase": "🔤",
    "input latin uppercase": "🔡",
    "input numbers": "🔠",
    "negative squared AB": "🆖",
    "negative squared OK": "🆗",
    "negative squared new": "🆙",
    "negative squared cool": "🆒",
    "negative squared fresh": "🆕",
    "negative squared free": "🆓",
    "keycap 0": "0️⃣",
    "keycap 1": "1️⃣",
    "keycap 2": "2️⃣",
    "keycap 3": "3️⃣",
    "keycap 4": "4️⃣",
    "keycap 5": "5️⃣",
    "keycap 6": "6️⃣",
    "keycap 7": "7️⃣",
    "keycap 8": "8️⃣",
    "keycap 9": "9️⃣",
    "keycap 10": "🔟",
    "keycap 1234": "🔢",
    "hash": "#️⃣",
    "asterisk": "*️⃣",
    "eject": "⏏️",
    "play button": "▶️",
    "pause button": "⏸",
    "play or pause button": "⏯",
    "stop button": "⏹",
    "record button": "⏺",
    "next track": "⏭",
    "previous track": "⏮",
    "fast forward": "⏩",
    "rewind": "⏪",
    "arrow up": "⏫",
    "arrow down": "⏬",
    "reverse button": "◀️",
    "upwards button": "🔼",
    "downwards button": "🔽",
    "arrow right": "➡️",
    "arrow left small": "⬅️",
    "arrow up small": "⬆️",
    "arrow down small": "⬇️",
    "arrow right up": "↗️",
    "arrow right down": "↘️",
    "arrow left down": "↙️",
    "arrow left up": "↖️",
    "arrow up down": "↕️",
    "left right arrow": "↔️",
    "right arrow curving left": "↪️",
    "left arrow curving right": "↩️",
    "arrow right curving up": "⤴️",
    "arrow left curving down": "⤵️",
    "shuffle tracks": "🔀",
    "repeat single": "🔁",
    "repeat": "🔂",
    "counterclockwise arrows button": "🔄",
    "clockwise arrows button": "🔃",
    "musical note": "🎵",
    "multiple musical notes": "🎶",
    "heavy plus sign": "➕",
    "heavy minus sign": "➖",
    "heavy division sign": "➗",
    "heavy multiplication sign": "✖️",
    "heavy equals sign": "🟰",
    "infinity": "♾",
    "dollar sign": "💲",
    "currency exchange": "💱",
    "trade mark": "™️",
    "copyright": "©️",
    "registered": "®️",
    "wavy dash": "〰️",
    "curly loop": "➰",
    "double curly loop": "➿",
    "end": "🔚",
    "back": "🔙",
    "on": "🔛",
    "top": "🔝",
    "soon": "🔜",
    "check mark button": "✔️",
    "ballot box with check": "☑️",
    "radio button": "🔘",
    "red circle": "🔴",
    "orange circle": "🟠",
    "yellow circle": "🟡",
    "green circle": "🟢",
    "blue circle": "🔵",
    "purple circle": "🟣",
    "black circle": "⚫️",
    "white circle": "⚪️",
    "brown circle": "🟤",
    "small red triangle": "🔺",
    "small downward triangle": "🔻",
    "small diamond": "🔸",
    "small blue diamond": "🔹",
    "small yellow diamond": "🔶",
    "small green diamond": "🔷",
    "white square": "🔳",
    "black square": "🔲",
    "black small square": "▪️",
    "white small square": "▫️",
    "black medium left-pointing triangle": "◾️",
    "white medium left-pointing triangle": "◽️",
    "black medium square": "◼️",
    "white medium square": "◻️",
    "red square": "🟥",
    "orange square": "🟧",
    "yellow square": "🟨",
    "green square": "🟩",
    "blue square": "🟦",
    "purple square": "🟪",
    "black large square": "⬛️",
    "white large square": "⬜️",
    "brown square": "🟫",
    "speaker": "🔈",
    "speaker with cancellation stroke": "🔇",
    "speaker with sound": "🔉",
    "loudspeaker": "🔊",
    "bell": "🔔",
    "bell with cancellation stroke": "🔕",
    "megaphone": "📣",
    "public address loudspeaker": "📢",
    "eye in speech bubble": "👁‍🗨",
    "speech balloon": "💬",
    "thought balloon": "💭",
    "cloud with lightning": "🗯",
    "spade suit": "♠️",
    "club suit": "♣️",
    "heart suit": "♥️",
    "diamond suit": "♦️",
    "joker": "🃏",
    "playing card": "🎴",
    "mahjong red dragon": "🀄️",
    "clock face one o'clock": "🕐",
    "clock face two o'clock": "🕑",
    "clock face three o'clock": "🕒",
    "clock face four o'clock": "🕓",
    "clock face five o'clock": "🕔",
    "clock face six o'clock": "🕕",
    "clock face seven o'clock": "🕖",
    "clock face eight o'clock": "🕗",
    "clock face nine o'clock": "🕘",
    "clock face ten o'clock": "🕙",
    "clock face eleven o'clock": "🕚",
    "clock face twelve o'clock": "🕛",
    "clock face one-thirty": "🕜",
    "clock face two-thirty": "🕝",
    "clock face three-thirty": "🕞",
    "clock face four-thirty": "🕟",
    "clock face five-thirty": "🕠",
    "clock face six-thirty": "🕡",
    "clock face seven-thirty": "🕢",
    "clock face eight-thirty": "🕣",
    "clock face nine-thirty": "🕤",
    "clock face ten-thirty": "🕥",
    "clock face eleven-thirty": "🕦",
    "clock face twelve-thirty": "🕧"
  },
  Flags: {
    "white flag": "🏳️",
    "black flag": "🏴",
    "chequered flag": "🏁",
    "triangular flag": "🚩",
    "rainbow flag": "🏳️‍🌈",
    "transgender flag": "🏳️‍⚧️",
    "pirate flag": "🏴‍☠️", 
    "flag afghanistan": "🇦🇫",
    "flag aker": "🇦🇽",
    "flag albania": "🇦🇱",
    "flag algeria": "🇩🇿",
    "flag american samoa": "🇦🇸",
    "flag andorra": "🇦🇩",
    "flag angola": "🇦🇴",
    "flag anguilla": "🇦🇮",
    "flag antartica": "🇦🇶",
    "flag antigua barbuda": "🇦🇬",
    "flag argentina": "🇦🇷",
    "flag armenia": "🇦🇲",
    "flag aruba": "🇦🇼",
    "flag australia": "🇦🇺",
    "flag austria": "🇦🇹",
    "flag azerbaijan": "🇦🇿",
    "flag bahamas": "🇧🇸",
    "flag bahrain": "🇧🇭",
    "flag bangladesh": "🇧🇩",
    "flag barbados": "🇧🇧",
    "flag belarus": "🇧🇾",
    "flag belgium": "🇧🇪",
    "flag belize": "🇧🇿",
    "flag benin": "🇧🇯",
    "flag bermuda": "🇧🇲",
    "flag bhutan": "🇧🇹",
    "flag bolivia": "🇧🇴",
    "flag bosnia herzegovina": "🇧🇦",
    "flag botswana": "🇧🇼",
    "flag brazil": "🇧🇷",
    "flag british indian ocean territory": "🇮🇴",
    "flag british virgin islands": "🇻🇬",
    "flag brunei": "🇧🇳",
    "flag bulgaria": "🇧🇬",
    "flag burkina faso": "🇧🇫",
    "flag burundi": "🇧🇮",
    "flag cambodia": "🇰🇭",
    "flag cameron": "🇨🇲",
    "flag canada": "🇨🇦",
    "flag canary islands": "🇮🇨",
    "flag cape verde": "🇨🇻",
    "flag caribbean netherlands": "🇧🇶",
    "flag cayman islands": "🇰🇾",
    "flag central african republic": "🇨🇫",
    "flag chad": "🇹🇩",
    "flag chile": "🇨🇱",
    "flag china": "🇨🇳",
    "flag christmas island": "🇨🇽",
    "flag cocos islands": "🇨🇨",
    "flag colombia": "🇨🇴",
    "flag comoros": "🇰🇲",
    "flag congo": "🇨🇬",
    "flag congo democratic republic": "🇨🇩",
    "flag cook islands": "🇨🇰",
    "flag costa rica": "🇨🇷",
    "flag cote divoire": "🇨🇮",
    "flag croatia": "🇭🇷",
    "flag cuba": "🇨🇺",
    "flag curacao": "🇨🇼",
    "flag cyprus": "🇨🇾",
    "flag czech republic": "🇨🇿",
    "flag denmark": "🇩🇰",
    "flag djibouti": "🇩🇯",
    "flag dominica": "🇩🇲",
    "flag dominican republic": "🇩🇴",
    "flag ecuador": "🇪🇨",
    "flag egypt": "🇪🇬",
    "flag el salvador": "🇸🇻",
    "flag equatorial guinea": "🇬🇶",
    "flag eritrea": "🇪🇷",
    "flag estonia": "🇪🇪",
    "flag ethiopia": "🇪🇹",
    "flag european union": "🇪🇺",
    "flag falkland islands": "🇫🇰",
    "flag faroe islands": "🇫🇴",
    "flag fiji": "🇫🇯",
    "flag finland": "🇫🇮",
    "flag france": "🇫🇷",
    "flag french guiana": "🇬🇫",
    "flag french polynesia": "🇵🇫",
    "flag french southern territories": "🇹🇫",
    "flag gabon": "🇬🇦",
    "flag gambia": "🇬🇲",
    "flag georgia": "🇬🇪",
    "flag germany": "🇩🇪",
    "flag ghana": "🇬🇭",
    "flag gibraltar": "🇬🇮",
    "flag greece": "🇬🇷",
    "flag greenland": "🇬🇱",
    "flag grenada": "🇬🇩",
    "flag guadeloupe": "🇬🇵",
    "flag guam": "🇬🇺",
    "flag guatemala": "🇬🇹",
    "flag guernsey": "🇬🇬",
    "flag guinea": "🇬🇳",
    "flag guinea bissau": "🇬🇼",
    "flag guyana": "🇬🇾",
    "flag haiti": "🇭🇹",
    "flag honduras": "🇭🇳",
    "flag hong kong": "🇭🇰",
    "flag hungary": "🇭🇺",
    "flag iceland": "🇮🇸",
    "flag india": "🇮🇳",
    "flag indonesia": "🇮🇩",
    "flag iran": "🇮🇷",
    "flag iraq": "🇮🇶",
    "flag ireland": "🇮🇪",
    "flag isle of man": "🇮🇲",
    "flag israel": "🇮🇱",
    "flag italy": "🇮🇹",
    "flag jamaica": "🇯🇲",
    "flag japan": "🇯🇵",
    "flag japanese crest": "🎌",
    "flag jersey": "🇯🇪",
    "flag jordan": "🇯🇴",
    "flag kazakhstan": "🇰🇿",
    "flag kenya": "🇰🇪",
    "flag kiribati": "🇰🇮",
    "flag kosovo": "🇽🇰",
    "flag kuwait": "🇰🇼",
    "flag kyrgyzstan": "🇰🇬",
    "flag laos": "🇱🇦",
    "flag latvia": "🇱🇻",
    "flag lebanon": "🇱🇧",
    "flag lesotho": "🇱🇸",
    "flag liberia": "🇱🇷",
    "flag libya": "🇱🇾",
    "flag liechtenstein": "🇱🇮",
    "flag lithuania": "🇱🇹",
    "flag luxembourg": "🇱🇺",
    "flag macau": "🇲🇴",
    "flag north macedonia": "🇲🇰",
    "flag madagascar": "🇲🇬",
    "flag malawi": "🇲🇼",
    "flag malaysia": "🇲🇾",
    "flag maldives": "🇲🇻",
    "flag mali": "🇲🇱",
    "flag malta": "🇲🇹",
    "flag marshall islands": "🇲🇭",
    "flag martinique": "🇲🇶",
    "flag mauritania": "🇲🇷",
    "flag mauritius": "🇲🇺",
    "flag mayotte": "🇾🇹",
    "flag mexico": "🇲🇽",
    "flag micronesia": "🇫🇲",
    "flag moldova": "🇲🇩",  
    "flag monaco": "🇲🇨",
    "flag mongolia": "🇲🇳",
    "flag montenegro": "🇲🇪",
    "flagMontserrat": "🇲🇸",
    "flag morocco": "🇲🇦",
    "flag mozambique": "🇲🇿",
    "flag myanmar": "🇲🇲",
    "flag namibia": "🇳🇦",
    "flag nauru": "🇳🇷",
    "flag nepal": "🇳🇵",
    "flag netherlands": "🇳🇱",
    "flag new caledonia": "🇳🇨",
    "flag new zealand": "🇳🇿",
    "flag nicaragua": "🇳🇮",
    "flag niger": "🇳🇪",
    "flag nigeria": "🇳🇬",
    "flag niue": "🇳🇺",
    "flag norfolk island": "🇳🇫",
    "flag north korea": "🇰🇵",
    "flag northern mariana islands": "🇲🇵",
    "flag norway": "🇳🇴",
    "flag oman": "🇴🇲",
    "flag pakistan": "🇵🇰",
    "flag palau": "🇵🇼",
    "flag palestine": "🇵🇸",
    "flag panama": "🇵🇦",
    "flag papua new guinea": "🇵🇬",
    "flag paraguay": "🇵🇾",
    "flag peru": "🇵🇪",
    "flag philippines": "🇵🇭",
    "flag pitcairn": "🇵🇳",
    "flag poland": "🇵🇱",
    "flag portugal": "🇵🇹",
    "flag puerto rico": "🇵🇷",
    "flag qatar": "🇶🇦",
    "flag reunion": "🇷🇪",
    "flag romania": "🇷🇴",
    "flag russia": "🇷🇺",
    "flag rwanda": "🇷🇼",
    "flag samoa": "🇼🇸",
    "flag san marino": "🇸🇲",
    "flag saudi arabia": "🇸🇦",
    "flag senegal": "🇸🇳",
    "flag serbia": "🇷🇸",
    "flag seychelles": "🇸🇨",
    "flag sierra leone": "🇸🇱",
    "flag singapore": "🇸🇬",
    "flag sint maarten": "🇸🇽",
    "flag slovakia": "🇸🇰",
    "flag slovenia": "🇸🇮",
    "flag south georgia": "🇬🇸",
    "flag south africa": "🇿🇦",
    "flag south korea": "🇰🇷",
    "flag south sudan": "🇸🇸",
    "flag spain": "🇪🇸",
    "flag sri lanka": "🇱🇰",
    "flag st barthelemy": "🇧🇱",
    "flag st helena": "🇸🇭",
    "flag st kitts nevis": "🇰🇳",
    "flag st lucia": "🇱🇨",
    "flag st martin": "🇵🇲",
    "flag st vincent": "🇻🇨",
    "flag sudan": "🇸🇩",
    "flag suriname": "🇸🇷",
    "flag sweden": "🇸🇪",
    "flag switzerland": "🇨🇭",
    "flag syria": "🇸🇾",
    "flag taiwan": "🇹🇼",
    "flag tajikistan": "🇹🇯",
    "flag tanzania": "🇹🇿",
    "flag thailand": "🇹🇭",
    "flag timor leste": "🇹🇱",
    "flag togo": "🇹🇬",
    "flag tokelau": "🇹🇰",
    "flag tonga": "🇹🇴",
    "flag trinidad tobago": "🇹🇹",
    "flag tunisia": "🇹🇳",
    "flag turkey": "🇹🇷",
    "flag turkmenistan": "🇹🇲",
    "flag turks caicos islands": "🇹🇨",
    "flag tuvalu": "🇹🇻",
    "flag us virgin islands": "🇻🇮",
    "flag uganda": "🇺🇬",
    "flag ukraine": "🇺🇦",
    "flag united arab emirates": "🇦🇪",
    "flag united kingdom": "🇬🇧",
    "flag united states": "🇺🇸",
    "flag uruguay": "🇺🇾",
    "flag uzbekistan": "🇺🇿",
    "flag vanuatu": "🇻🇺",
    "flag vatican city": "🇻🇦",
    "flag venezuela": "🇻🇪",
    "flag vietnam": "🇻🇳",
    "flag wallis futuna": "🇼🇫",
    "flag western sahara": "🇪🇭",
    "flag yemen": "🇾🇪",
    "flag zambia": "🇿🇲",
    "flag zimbabwe": "🇿🇼"
  }
}

const emojiData: EmojiMap = {
  ":ban:": "/furrchat/assets/smilies/ban.gif",
  ":bday:": "/furrchat/assets/smilies/bdaybiggrin.gif",
  ":beer:": "/furrchat/assets/smilies/bier.gif",
  ":chubby:": "/furrchat/assets/smilies/chubby.gif",
  ":clown:": "/furrchat/assets/smilies/clown.gif",
  ":confused:": "/furrchat/assets/smilies/confused.gif",
  ":cool:": "/furrchat/assets/smilies/coool.gif",
  ":devilwhip:": "/furrchat/assets/smilies/devil_whip.gif",
  ":devil:": "/furrchat/assets/smilies/devil.gif",
  ":spain:": "/furrchat/assets/smilies/es.png",
  ":finland:": "/furrchat/assets/smilies/fi.png",
  ":france:": "/furrchat/assets/smilies/fr.png",
  ":frown:": "/furrchat/assets/smilies/frown.gif",
  ":frusty:": "/furrchat/assets/smilies/frusty.gif",
  ":fyou:": "/furrchat/assets/smilies/fyou.gif",
  ":hooligan:": "/furrchat/assets/smilies/got-hooligan.gif",
  ":headshakefast:": "/furrchat/assets/smilies/headshakesmile-fast.gif",
  ":hypocrite:": "/furrchat/assets/smilies/hypocrite2.gif",
  ":king:": "/furrchat/assets/smilies/koning.gif",
  ":skorea:": "/furrchat/assets/smilies/kr.png",
  ":drool:": "/furrchat/assets/smilies/kwijl.gif",
  ":list:": "/furrchat/assets/smilies/lijstje.gif",
  ":loveit:": "/furrchat/assets/smilies/loveit.gif",
  ":lurk:": "/furrchat/assets/smilies/lurk.gif",
  ":marry:": "/furrchat/assets/smilies/marrysmile.gif",
  ":nerd:": "/furrchat/assets/smilies/nerd.png",
  ":noo:": "/furrchat/assets/smilies/nooo.gif",
  ":nothumbs:": "/furrchat/assets/smilies/nosthumbs.gif",
  ":offtopic:": "/furrchat/assets/smilies/offtopic.gif",
  ":service:": "/furrchat/assets/smilies/pimatyourservice.gif",
  ":poland:": "/furrchat/assets/smilies/pl.png",
  ":die:": "/furrchat/assets/smilies/plzdie.gif",
  ":puh:": "/furrchat/assets/smilies/puh.gif",
  ":puh2:": "/furrchat/assets/smilies/puh2.gif",
  ":puhbye:": "/furrchat/assets/smilies/puhbye.gif",
  ":puke:": "/furrchat/assets/smilies/pukey.gif",
  ":cow:": "/furrchat/assets/smilies/rc5.gif",
  ":redcard:": "/furrchat/assets/smilies/redcard.gif",
  ":bored:": "/furrchat/assets/smilies/saai.gif",
  ":shiny:": "/furrchat/assets/smilies/shiny.gif",
  ":sleeping:": "/furrchat/assets/smilies/slapen.gif",
  ":zzz:": "/furrchat/assets/smilies/sleepey.gif",
  ":sleephappy:": "/furrchat/assets/smilies/sleephappy.gif",
  ":snap:": "/furrchat/assets/smilies/smiliecam.gif",
  ":steam:": "/furrchat/assets/smilies/steam.gif",
  ":toilet_puke:": "/furrchat/assets/smilies/toilet-puke.gif",
  ":wink:": "/furrchat/assets/smilies/wink.gif",
  ":winkthumbs:": "/furrchat/assets/smilies/winkthumbs.gif",
  ":worship:": "/furrchat/assets/smilies/worshippy.gif",
  ":yawn:": "/furrchat/assets/smilies/yawnee.gif",
  ":yes:": "/furrchat/assets/smilies/yes.gif",
  ":yum:": "/furrchat/assets/smilies/yummie.gif",
  ":zoom:": "/furrchat/assets/smilies/zoefzoef.gif",
};

const discordEmojis: EmojiMap = {
  ":ea:": "<:3a:1251187519882662012>",
  ":3:": "<:3:1226320165302571087>",
  ":debugman:": "<:DebugMan:1226320526037880916>",
  ":garftrue:": "<:GarfTrue:1228207760047472670>",
  ":100:": "<a:MiscHundred:1226319950570983434>",
  ":POWER:": "<:POWER:1215322815105077279>",
  ":cat:aaa:": "<:aaaaaaaaaaa:1149352246572761120>",
  ":acatonmeower:": "<:acatonmeower:1021912187163394138>",
  ":ameowdundundun:": "<a:ameowdundundun:1226319768236331140>",
  ":amogos:": "<:amogos:1226314396377288726>",
  ":angular:": "<:angular:1255562415958130768>",
  ":atticus:": "<:atticus:1221630557369405440>",
  ":atticusaijkndemw:": "<:atticusaijkndemw:1212216821625917450>",
  ":bear:": "<:bear:1255229843126358016>",
  ":blank:": "<:blank:1018231234553446411>",
  ":blobheart:": "<:blobheart:1226319886867763240>",
  ":bluray:": "<:bluray:1255229893625643140>",
  ":boogie:": "<a:boogie:1226311710818959401>",
  ":bred:": "<:bred:959422100458844160>",
  ":catlick:": "<:catlick:1180505322851414206>",
  ":caughtin4k:": "<a:caughtin4k:1102387987838402574>",
  ":cd:": "<:cd:1255229891893395457>",
  ":chainbrokerestartingnow:": "<:chainbrokerestartingnow:1149502765542953021>",
  ":cheese:": "<:cheese:1255229898617000067>",
  ":consume:": "<:consume:1224195139082125322>",
  ":cta:": "<:cta:1226913189590073494>",
  ":cydia:": "<:cydia:1227268820213698611>",
  ":dango:": "<:dango:1254883210643374263>",
  ":darkstar:": "<:darkstar:957320841044045905>",
  ":demonetized:": "<:demonetized:1226320307673894953>",
  ":downvote:": "<:downvote:1010035793819091068>",
  ":drinkmilk:": "<:drinkmilk:1151681105615929435>",
  ":drunkmeow:": "<:drunkmeow:1026159952038985829>",
  ":duckspinningcube:": "<a:duckspinningcube:1152410546893770783>",
  ":ducky:": "<:ducky:1001974772051234950>",
  ":duckyspeen:": "<a:duckyspeen:995024774348668968>",
  ":dvd:": "<:dvd:1251187522432798808>",
  ":eepy:": "<:eepy:1254884335514030212>",
  ":finalboss:": "<:finalboss:954783074586095636>",
  ":flipper:": "<:flipper:1011498926819520572>",
  ":fortune:": "<:fortune:1210379302328078356>",
  ":freya:": "<:freya:1244778372953935922>",
  ":fubgingcloudlink:": "<:fubgingcloudlink:1224195287178936392>",
  ":goobert:": "<:goobert:1254882434898464922>",
  ":goobertyuhhuh:": "<:goobertyuhhuh:1255229895726858273>",
  ":gun:": "<:gun:1015228426778578966>",
  ":halfstar:": "<:halfstar:957320841241169991>",
  ":happymeow:": "<:happymeow:954779471330816040>",
  ":harry:": "<:harry:1251187517433057411>",
  ":hat:": "<:hat:1251187521140949083>",
  ":hooray:": "<a:hooray:1230023947777609808>",
  ":kick:": "<a:kick:1231078387704139967>",
  ":luna:": "<:luna:1221632755851591740>",
  ":madmeow:": "<:madmeow:954780476067946638>",
  ":mainispain:": "<:mainispain:939326396977795113>",
  ":marker:": "<:marker:1238203265229914132>",
  ":me:": "<:me:1221628997025267752>",
  ":melm:": "<:melm:1248842290806657035>",
  ":meo:": "<:meo:1255229897463431198>",
  ":meowspin:": "<:meowspin:1017901487810170940>",
  ":meowy2:": "<:meowy2:1214405335666925568>",
  ":meowybutton:": "<:meowybutton:950192902708019200>",
  ":meowyhadsomepepsi:": "<:meowyhadsomepepsi:1224195086951383113>",
  ":meowyplanet:": "<a:meowyplanet:1008194232282009640>",
  ":meowyplanets:": "<a:meowyplanets:1008194354197831800>",
  ":meowyspin:": "<a:meowyspin:1008194132067483678>",
  ":meowytroll:": "<:meowytroll:1111415513462079628>",
  ":miau:": "<:miau:1237207275870097519>",
  ":mikeisgettingsickofyou:": "<:mikeisgettingsickofyou:1143348848085962855>",
  ":noodle:": "<:noodle:1227131494183473233>",
  ":notstonks:": "<:notstonks:1255200842894803075>",
  ":nuhhuh:": "<:nuhhuh:1233290735999258664>",
  ":octocat:": "<:octocat:1254884597724872764>",
  ":oswal:": "<:oswal:1226912603931148338>",
  ":ow:": "<:ow:1251723597630931065>",
  ":penguinmod:": "<:penguinmod:1255200838008442890>",
  ":pixelmeowy:": "<:pixelmeowy:1125502216090951840>",
  ":planktonpog:": "<:planktonpog:995896283833323520>",
  ":progresspride:": "<:progresspride:1255562425625870397>",
  ":qbabyblue:": "<:qbabyblue:1255190936376578149>",
  ":qbabyorange:": "<:qbabyorange:1255190939429896192>",
  ":qbabypink:": "<:qbabypink:1255190938108821514>",
  ":qbby:": "<:qbby:1255190940570882089>",
  ":quacker:": "<:quacker:959421966148857906>",
  ":qucy:": "<:qucy:1255190933721579591>",
  ":qudy:": "<:qudy:1255190934975418519>",
  ":ratestar:": "<:ratestar:957320841538982018>",
  ":react:": "<:react:1255562420697567334>",
  ":rehehehehehehe:": "<:rehehehehehehe:1123971249442406521>",
  ":robotop:": "<:robotop:1148967341409976411>",
  ":ron:": "<:ron:1251187515189104730>",
  ":roxy:": "<:roxy:1260366574989348955>",
  ":sadmeow:": "<:sadmeow:954781179704393769>",
  ":scratch:": "<:scratch:1255200839975567483>",
  ":sd:": "<:sd:1255229890651881492>",
  ":shake:": "<a:shake:1227279789472354435>",
  ":shakespeare:": "<:shakespeare:982709311702716457>",
  ":shark:": "<:shark:1260009179024855081>",
  ":soon:": "<:soon:932400780072349726>",
  ":sphere:": "<a:sphere:1227279796715917362>",
  ":spin:": "<a:spin:1227279798015889498>",
  ":squish:": "<a:squish:1227279787072946189>",
  ":stonks:": "<:stonks:1251187639504343040>",
  ":stretchcat:": "<:stretchcat:1210253516417798194>",
  ":sus:": "<:sus:1199167654972375090>",
  ":svelte:": "<:svelte:1255562419397464145>",
  ":tehduck:": "<:tehduck:1055226916409458808>",
  ":thehorror:": "<:thehorror:1158484835090833508>",
  ":think:": "<:think:1226311619064234086>",
  ":this:": "<:this:1068710522561773719>",
  ":thubsup:": "<:thubsup:1229994631840927774>",
  ":toasty:": "<:toasty:1226314396377288726>",
  ":treboog:": "<:treboog:1254882433900351533>",
  ":treboogyuhhuh:": "<:treboogyuhhuh:1255229894733070346>",
  ":trol:": "<:trol:1010322254065848361>",
  ":trolleyproblem:": "<:trolleyproblem:1255562426653478953>",
  ":turbowarp:": "<:turbowarp:1255200839170261032>",
  ":uggh:": "<:uggh:1227845267496243242>",
  ":upvote:": "<:upvote:1010035340851023892>",
  ":vue:": "<:vue:1255562417694441553>",
  ":wallace:": "<:wallace:1254884015014674585>",
  ":waluigi:": "<:waluigi:1255562422580805634>",
  ":wario:": "<:wario:1255562424241618944>",
  ":whar:": "<:whar:1143938761919570000>",
  ":wiwwy:": "<:wiwwy:953882510167773184>",
  ":wooftheheck:": "<:wooftheheck:1217544930847625427>",
  ":wow:": "<:wow:952755842095132752>",
  ":yippe:": "<a:yippe:1226318495147495505>",
  ":yuhhuh2:": "<:yuhhuh:1227131494183473233>",
  ":yuhhuh:": "<:yuhhuh:1227268820213698611>",
  ":zed:": "<:zed:1208625071766114364>",
  ":snooga1:": "<:snooga1:1258860425294909442>",
  ":snooga2:": "<:snooga2:1258860426997797006>",
  ":snooga3:": "<:snooga3:1258860428122132556>",
  ":snooga4:": "<:snooga4:1258860429703385108>",
  ":snooga5:": "<:snooga5:1258860431284502628>",
  ":snooga6:": "<:snooga6:1258860432719085638>",
  ":snooga7:": "<:snooga7:1258860434497343590>",
  ":snooga8:": "<:snooga8:1258860443468824616>",
  ":doinkus:": "<:doinkus:1266027105452560444>",
  ":doinkus2": "<:doinkus:1267307216000782457>",
  ":green:": "<:green:1266027100905803776>",
  ":garf:": "<:garf:1266027104273825863>",
  ":proton:": "<:proton:1266027095042166864>",
  ":shocc:": "<:shocc:1266027587704983593>",
  ":mikehmm:": "<:mikehmm:1266027099433472061>",
  ":hidingcar:": "<:hidingcar:1266027448869322793>",
};

const GIFS: EmojiMap = {
  "Hello Chat!":
    "https://uploads.meower.org/attachments/E1vZKv7jDxcd2P1LdsbiVsLP/image0.gif",
  "Bye Chat!":
    "https://uploads.meower.org/attachments/mdgjL1irwbEJP6kC7lencoMd/image1.gif",
  "Whar?!": "https://media1.tenor.com/m/U8OLnFKZmrgAAAAd/shocked-surprised.gif",
  stare: "https://media.tenor.com/DFfCL02_DCcAAAAM/cat-look.gif",
  "dancing Y":
    "https://media.tenor.com/9zMHtfQLsjUAAAAi/capital-letter-letter.gif",
  "dancing E":
    "https://media.tenor.com/A5a-G4IqGOQAAAAi/dancing-letter-letter-e.gif",
  "dancing S":
    "https://media.tenor.com/IQQVfdxyOIQAAAAi/dancing-letter-letter.gif",
  "when u no answr":
    "https://uploads.meower.org/attachments/6p3e97Ai6zXzFlXFTjn0PKfr/gif",
  chippyyyy: "https://i.ibb.co/d4TsM8J/cat-chips.gif",
  "water car": "https://media1.tenor.com/m/dDu9uYP_2i0AAAAC/water-cat-cat.gif",
  "goofy cat": "https://media1.tenor.com/m/cor0ZSgUarIAAAAd/cat-goofy-cat.gif",
  "scary car": "https://media1.tenor.com/m/a37YNvV0XaAAAAAd/cat-black-fur.gif",
  "blast car": "https://media1.tenor.com/m/XCKZfD-GO48AAAAC/cat-blast-off.gif",
  lasercat: "https://media1.tenor.com/m/MzjQEZ1tPZ4AAAAC/cat-lasers.gif",
  nocommen: "https://media1.tenor.com/m/719_X3doMAoAAAAd/black-cat.gif",
  hirecattostareatu:
    "https://media1.tenor.com/m/PmpiSvg8bDAAAAAC/i-hired-this-cat-to-stare-at-you-hired.gif",
  "willsmith-slap":
    "https://gifdb.com/images/high/will-smith-slaps-chris-rock-9tdpd79yfmrq5p39.gif",
  "took-a-chunk":
    "https://uploads.meower.org/attachments/GrjtUveRiUr7mCARZIR4EGEf/mower.png",
  bunger:
    "https://uploads.meower.org/attachments/qA8nsPQ0ifB3is13YTD7WQxV/bunger.gif",
};

const defaultPFPS: { [key: number]: string } = {
  101: "/furrchat/assets/default_pfps/101-x9fRmybQ.svg",
  102: "/furrchat/assets/default_pfps/download (1).svg",
  500: "/furrchat/assets/default_pfps/download (2).svg",
  '-3': "/furrchat/assets/default_pfps/download (3).svg",
  34: "/furrchat/assets/default_pfps/icon_33-aa0b2afc.svg",
  33: "/furrchat/assets/default_pfps/icon_32-b04ea763.svg",
  32: "/furrchat/assets/default_pfps/icon_31-69ab1d48.svg",
  31: "/furrchat/assets/default_pfps/icon_30-bb20f655.svg",
  30: "/furrchat/assets/default_pfps/icon_29-3b90bc5e.svg",
  29: "/furrchat/assets/default_pfps/icon_28-aba3f2a4.svg",
  28: "/furrchat/assets/default_pfps/icon_27-89761f19.svg",
  27: "/furrchat/assets/default_pfps/icon_26-ff79861f.svg",
  26: "/furrchat/assets/default_pfps/icon_25-cc78b147.svg",
  25: "/furrchat/assets/default_pfps/icon_24-6026f708.svg",
  24: "/furrchat/assets/default_pfps/icon_23-cd7c45d1.svg",
  23: "/furrchat/assets/default_pfps/icon_22-119ec697.svg",
  22: "/furrchat/assets/default_pfps/icon_21-2ef6b9a3.svg",
  21: "/furrchat/assets/default_pfps/icon_20-d1301d19.svg",
  20: "/furrchat/assets/default_pfps/icon_19-8ad18d14.svg",
  19: "/furrchat/assets/default_pfps/icon_18-dc1f4b4e.svg",
  18: "/furrchat/assets/default_pfps/icon_17-39e35340.svg",
  17: "/furrchat/assets/default_pfps/icon_16-e5e55f53.svg",
  16: "/furrchat/assets/default_pfps/icon_15-d1b06a28.svg",
  15: "/furrchat/assets/default_pfps/icon_14-6513f659.svg",
  14: "/furrchat/assets/default_pfps/icon_13-58e2dcbb.svg",
  13: "/furrchat/assets/default_pfps/icon_12-0f7ed126.svg",
  12: "/furrchat/assets/default_pfps/icon_11-521812d2.svg",
  11: "/furrchat/assets/default_pfps/icon_10-4bd3e33c.svg",
  10: "/furrchat/assets/default_pfps/icon_9-25c74dcc.svg",
  9: "/furrchat/assets/default_pfps/icon_8-515d5ae7.svg",
  8: "/furrchat/assets/default_pfps/icon_7-16e301c0.svg",
  7: "/furrchat/assets/default_pfps/icon_6-d72d5ba2.svg",
  6: "/furrchat/assets/default_pfps/icon_5-656d31e0.svg",
  5: "/furrchat/assets/default_pfps/icon_4-078d1185.svg",
  4: "/furrchat/assets/default_pfps/icon_3-79effa11.svg",
  3: "/furrchat/assets/default_pfps/icon_2-03a60034.svg",
  2: "/furrchat/assets/default_pfps/icon_1-3649891f.svg",
  1: "/furrchat/assets/default_pfps/icon_0-ab82a5ad.svg",
};

const userEmojis: EmojiMap = {
  Souple: "👑",
  ij: "👑",
  noodles: "🧀",
  kiwi: "🥝",
  cat: "🐱",
};

const PBJTime: EmojiMap = {
  ":banana:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time.gif",
  ":redbanana:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-1.gif",
  ":superbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-2.gif",
  ":babybanana:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-3.gif",
  ":banana2:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-4.gif",
  ":legstretchbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-6.gif",
  ":hulabanana:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-7.gif",
  ":manybananas:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-8.gif",
  ":grandpabanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-9.gif",
  ":banana3:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-10.gif",
  ":elvisbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-11.gif",
  ":explodbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-12.gif",
  ":banana4:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-13.gif",
  ":santabanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-14.gif",
  ":bananaSMASH:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-15.gif",
  ":alienbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-16.gif",
  ":firebanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-17.gif",
  ":derpybanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-18.gif",
  ":bananadance4:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-19.gif",
  ":bananadance5:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-20.gif",
  ":bananadance6:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-21.gif",
  ":bananadance7:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-22.gif",
  ":bananadance8:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-23.gif",
  ":bananadance9:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-24.gif",
  ":carrotbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-25.gif",
  ":bananadance11:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-26.gif",
  ":bananadance12:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-27.gif",
  ":bananaoncow:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-28.gif",
  ":bananadance14:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-30.gif",
  ":bananadance15:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-32.gif",
  ":bananadevil:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-33.gif",
  ":bananadance17:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-36.gif",
  ":bananadance18:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-37.gif",
  ":bananadance19:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-38.gif",
  ":bananadance20:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-39.gif",
  ":bananadance21:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-40.gif",
  ":bananadance26:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-41.gif",
  ":bananaoncomputer:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-42.gif",
  ":bananadance28:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-43.gif",
  ":jumpinjackbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-44.gif",
  ":bananadance30:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-45.gif",
  ":bananadance31:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-46.gif",
  ":justbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-47.gif",
  ":bananamailslot:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-48.gif",
  ":bananadance34:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-49.gif",
  ":bananadance35:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-50.gif",
  ":bananadance36:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-51.gif",
  ":bananadance38:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-53.gif",
  ":bananadance39:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-54.gif",
  ":bananadance40:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-55.gif",
  ":bananadance41:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-56.gif",
  ":bananadance42:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-57.gif",
  ":bananadance43:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-58.gif",
  ":bananadance44:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-59.gif",
  ":bananadance45:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-60.gif",
  ":LAME:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-62.gif",
  ":bananadance48:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-63.gif",
  ":bananadance51:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-66.gif",
  ":bananadance52:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-67.gif",
  ":bananadance53:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-68.gif",
  ":militarybanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-69.gif",
  ":bananadance55:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-70.gif",
  ":wavingbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-71.gif",
  ":bananawaving:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-72.gif",
  ":bananadance58:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-73.gif",
  ":bananawithwhip:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-74.gif",
  ":bananaonllama:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-75.gif",
  ":bananadance61:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-76.gif",
  ":tusors:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-77.gif",
  ":bananadance63:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-78.gif",
  ":bananadance65:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-80.gif",
  ":bananadance68:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-83.gif",
  ":broccolinana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-85.gif",
  ":bananadance71:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-86.gif",
  ":batnana:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-88.gif",
  ":smooshedbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-89.gif",
  ":bananadance75:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-90.gif",
  ":bananadance76:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-91.gif",
  ":bananadance78:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-93.gif",
  ":nobanana:": "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-94.gif",
  ":jumpingbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-95.gif",
  ":bananadance82:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-97.gif",
  ":bananadance83:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-98.gif",
  ":bananadance85:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-100.gif",
  ":bananadance86:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-101.gif",
  ":bananadance87:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-102.gif",
  ":bananainelevator:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-103.gif",
  ":bananadance90:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-105.gif",
  ":upsidedownbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-106.gif",
  ":bananadance92:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-107.gif",
  ":jetpackbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-108.gif",
  ":bananadance96:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-111.gif",
  ":bananadance97:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-112.gif",
  ":bananadance99:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-114.gif",
  ":bananadance100:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-115.gif",
  ":bananadance105:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-120.gif",
  ":bananadance107:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-122.gif",
  ":goblinbanana:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-124.gif",
  ":bananadance110:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-125.gif",
  ":bananadance111:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-126.gif",
  ":bananadance112:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-127.gif",
  ":bananadance113:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-128.gif",
  ":bananadance115:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-130.gif",
  ":bananadance116:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-131.gif",
  ":bananadance117:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-132.gif",
  ":bananadance118:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-133.gif",
  ":bananadance120:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-135.gif",
  ":bananadance121:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-136.gif",
  ":bananadance122:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-137.gif",
  ":bananadance123:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-138.gif",
  ":bananadance124:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-139.gif",
  ":bananadance125:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-140.gif",
  ":bananadissappearing:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-141.gif",
  ":bananadance127:":
    "/furrchat/assets/smilies-pbj/peanut-butter-jelly-time-142.gif",
};

const headingOptions = [
  { label: "Heading 1", value: "#" },
  { label: "Heading 2", value: "##" },
  { label: "Heading 3", value: "###" },
  { label: "Heading 4", value: "####" },
  { label: "Heading 5", value: "#####" },
  { label: "Heading 6", value: "######" },
];

const musicLibrary = [
  {
    path: "/furrchat/assets/bgm/meowerisnotdead.mp3",
    author: "Voxalice",
    songName: "Meower is (not) dead"
  },
  {
    path: "/furrchat/assets/bgm/meowerisnotdeadinstrumental.wav",
    author: "Voxalice",
    songName: "Meower is (not) dead Instrumental"
  },
  {
    path: "/furrchat/assets/bgm/meowerjohnelr.mp3",
    author: "Johnelr",
    songName: "Meower."
  },
  {
    path: "/furrchat/assets/bgm/nightsky.wav",
    author: "Meguy7878",
    songName: "Night Sky"
  },
  {
    path: "/furrchat/assets/bgm/pbloopremix.wav",
    author: "Johnelr",
    songName: "P.B loop remix"
  },
  {
    path: "/furrchat/assets/bgm/percussionbaseloop.wav",
    author: "Voxalice",
    songName: "Percussion bass loop"
  },
  {
    path: "/furrchat/assets/bgm/pianoeargrapes.mp3",
    author: "Maclator",
    songName: "Piano ear grapes"
  },
  {
    path: "/furrchat/assets/bgm/theelevatoroftime.wav",
    author: "Voxalice",
    songName: "The elevator of time"
  },
  {
    path: "/furrchat/assets/bgm/untitledsong1.wav",
    author: "TheStrykerJay",
    songName: "Untitled Song 1"
  },
  {
    path: "/furrchat/assets/bgm/untitledsong2.mp3",
    author: "Dotumantaraye",
    songName: "Untitled Song 2"
  },
];

export {
  emojiData,
  discordEmojis,
  GIFS,
  userEmojis,
  headingOptions,
  PBJTime,
  defaultPFPS,
  musicLibrary,
  realEmojis
};