type EmojiMap = { [key: string]: string }; // Interface for emoji key-value pairs

const emojiData: EmojiMap = {
    "lick": "/furrchat/assets/smilies/a_puh.gif",
    "ban": "/furrchat/assets/smilies/ban.gif",
    "bday": "/furrchat/assets/smilies/bdaybiggrin.gif",
    "beer": "/furrchat/assets/smilies/bier.gif",
    "chubby": "/furrchat/assets/smilies/chubby.gif",
    "clown": "/furrchat/assets/smilies/clown.gif",
    "confused": "/furrchat/assets/smilies/confused.gif",
    "cool": "/furrchat/assets/smilies/coool.gif",
    "devilwhip": "/furrchat/assets/smilies/devil_whip.gif",
    "devil": "/furrchat/assets/smilies/devil.gif",
    "spain": "/furrchat/assets/smilies/es.gif",
    "finland": "/furrchat/assets/smilies/fi.gif",
    "france": "/furrchat/assets/smilies/fr.gif",
    "frown": "/furrchat/assets/smilies/frown.gif",
    "frusty": "/furrchat/assets/smilies/frusty.gif",
    "fyou": "/furrchat/assets/smilies/fyou.gif",
    "hooligan": "/furrchat/assets/smilies/got-hooligan.gif",
    "headshake_fast": "/furrchat/assets/smilies/headshakesmile-fast.gif",
    "hypocrite": "/furrchat/assets/smilies/hypocrite2.gif",
    "king": "/furrchat/assets/smilies/koning.gif",
    "southkorea": "/furrchat/assets/smilies/kr.png",
    "drool": "/furrchat/assets/smilies/kwijl.gif",
    "list": "/furrchat/assets/smilies/lijstje.gif",
    "loveit": "/furrchat/assets/smilies/loveit.gif",
    "lurk": "/furrchat/assets/smilies/lurk.gif",
    "marry": "/furrchat/assets/smilies/marrysmile.gif",
    "noo": "/furrchat/assets/smilies/nooo.gif",
    "nothumbs": "/furrchat/assets/smilies/nosthumbs.gif",
    "offtopic": "/furrchat/assets/smilies/offtopic.gif",
    "service": "/furrchat/assets/smilies/pimatyourservice.gif",
    "poland": "/furrchat/assets/smilies/pl.png",
    "plzdie": "/furrchat/assets/smilies/plzdie.gif",
    "puh": "/furrchat/assets/smilies/puh.gif",
    "puh2": "/furrchat/assets/smilies/puh2.gif",
    "puhbye": "/furrchat/assets/smilies/puhbye.gif",
    "puke": "/furrchat/assets/smilies/pukey.gif",
    "cow": "/furrchat/assets/smilies/rc5.gif",
    "redcard": "/furrchat/assets/smilies/redcard.gif",
    "bored": "/furrchat/assets/smilies/saai.gif",
    "shiny": "/furrchat/assets/smilies/shiny.gif",
    "sleeping": "/furrchat/assets/smilies/slapen.gif",
    "zzz": "/furrchat/assets/smilies/sleepey.gif",
    "sleephappy": "/furrchat/assets/smilies/sleephappy.gif",
    "smile": "/furrchat/assets/smilies/smile.gif",
    "snap": "/furrchat/assets/smilies/smiliecam.gif",
    "steam": "/furrchat/assets/smilies/steam.gif",
    "toilet_puke": "/furrchat/assets/smilies/toilet-puke.gif",
    "wink": "/furrchat/assets/smilies/wink.gif",
    "winkthumbs": "/furrchat/assets/smilies/winkthumbs.gif",
    "worship": "/furrchat/assets/smilies/worshippy.gif",
    "yawn": "/furrchat/assets/smilies/yawnee.gif",
    "yes": "/furrchat/assets/smilies/yes.gif",
    "yum": "/furrchat/assets/smilies/yummie.gif",
    "zoom": "/furrchat/assets/smilies/zoefzoef.gif",
  };

  let defaultPFPS: string[] = [
    '/furrchat/assets/default_pfps/icon_33-aa0b2afc.svg',
    '/furrchat/assets/default_pfps/icon_32-b04ea763.svg',
    '/furrchat/assets/default_pfps/icon_31-69ab1d48.svg',
    '/furrchat/assets/default_pfps/icon_30-bb20f655.svg',
    '/furrchat/assets/default_pfps/icon_29-3b90bc5e.svg',
    '/furrchat/assets/default_pfps/icon_28-aba3f2a4.svg',
    '/furrchat/assets/default_pfps/icon_27-89761f19.svg',
    '/furrchat/assets/default_pfps/icon_26-ff79861f.svg',
    '/furrchat/assets/default_pfps/icon_25-cc78b147.svg',
    '/furrchat/assets/default_pfps/icon_24-6026f708.svg',
    '/furrchat/assets/default_pfps/icon_23-cd7c45d1.svg',
    '/furrchat/assets/default_pfps/icon_22-119ec697.svg',
    '/furrchat/assets/default_pfps/icon_21-2ef6b9a3.svg',
    '/furrchat/assets/default_pfps/icon_20-d1301d19.svg',
    '/furrchat/assets/default_pfps/icon_19-8ad18d14.svg',
    '/furrchat/assets/default_pfps/icon_18-dc1f4b4e.svg',
    '/furrchat/assets/default_pfps/icon_17-39e35340.svg',
    '/furrchat/assets/default_pfps/icon_16-e5e55f53.svg',
    '/furrchat/assets/default_pfps/icon_15-d1b06a28.svg',
    '/furrchat/assets/default_pfps/icon_14-6513f659.svg',
    '/furrchat/assets/default_pfps/icon_13-58e2dcbb.svg',
    '/furrchat/assets/default_pfps/icon_12-0f7ed126.svg',
    '/furrchat/assets/default_pfps/icon_11-521812d2.svg',
    '/furrchat/assets/default_pfps/icon_10-4bd3e33c.svg',
    '/furrchat/assets/default_pfps/icon_9-25c74dcc.svg',
    '/furrchat/assets/default_pfps/icon_8-515d5ae7.svg',
    '/furrchat/assets/default_pfps/icon_7-16e301c0.svg',
    '/furrchat/assets/default_pfps/icon_6-d72d5ba2.svg',
    '/furrchat/assets/default_pfps/icon_5-656d31e0.svg',
    '/furrchat/assets/default_pfps/icon_4-078d1185.svg',
    '/furrchat/assets/default_pfps/icon_3-79effa11.svg',
    '/furrchat/assets/default_pfps/icon_2-03a60034.svg',
    '/furrchat/assets/default_pfps/icon_1-3649891f.svg',
    '/furrchat/assets/default_pfps/icon_0-ab82a5ad.svg',
  ];
  
export default defaultPFPS; emojiData;